export const feedData = [
  {
    id: 1,
    name: "Shubham",
    city: "Jaipur",
    state: "Rajasthan",
    gender: "M",
  },
  {
    id: 2,
    name: "Master",
    city: "Bhopal",
    state: "Madhya Pradesh",
    gender: "M",
  },
  {
    id: 3,
    name: "Mickey",
    city: "Mumbai",
    state: "Maharashtra",
    gender: "M",
  },
  {
    id: 4,
    name: "Singodiya",
    city: "Lucknow",
    state: "Uttar Pradesh",
    gender: "M",
  },
  {
    id: 5,
    name: "Anonymo.",
    city: "Chennai",
    state: "Tamil Nadu",
    gender: "F",
  },
  {
    id: 8,
    name: "Shree Ji",
    city: "Patna",
    state: "Bihar",
    gender: "M",
  },
  {
    id: 9,
    name: "Kanuda",
    city: "Gandhinagar",
    state: "Gujarat",
    gender: "M",
  },
  {
    id: 11,
    name: "Premswaroopa",
    city: "Hyderabad",
    state: "Telangana",
    gender: "F",
  },
  {
    id: 12,
    name: "Anonymous",
    city: "Kolkata",
    state: "West Bengal",
    gender: "F",
  },
  {
    id: 13,
    name: "Shree Ji",
    city: "Thiruvananthapuram",
    state: "Kerala",
    gender: "M",
  },
  {
    id: 14,
    name: "Kanuda",
    city: "Panjim",
    state: "Goa",
    gender: "M",
  },
  {
    id: 15,
    name: "Premswaroopa",
    city: "Dehradun",
    state: "Uttarakhand",
    gender: "F",
  },
  {
    id: 16,
    name: "Anonymous",
    city: "Shimla",
    state: "Himachal Pradesh",
    gender: "F",
  },
  {
    id: 17,
    name: "Shree Ji",
    city: "Pune",
    state: "Maharashtra",
    gender: "M",
  },
];

export const indianStatesMap = {
  "Andhra Pradesh": "AP",
  "Arunachal Pradesh": "AR",
  Assam: "AS",
  Bihar: "BR",
  Chhattisgarh: "CG",
  Goa: "GA",
  Gujarat: "GJ",
  Haryana: "HR",
  "Himachal Pradesh": "HP",
  Jharkhand: "JH",
  Karnataka: "KA",
  Kerala: "KL",
  "Madhya Pradesh": "MP",
  Maharashtra: "MH",
  Manipur: "MN",
  Meghalaya: "ML",
  Mizoram: "MZ",
  Nagaland: "NL",
  Odisha: "OR",
  Punjab: "PB",
  Rajasthan: "RJ",
  Sikkim: "SK",
  "Tamil Nadu": "TN",
  Telangana: "TG",
  Tripura: "TR",
  "Uttar Pradesh": "UP",
  Uttarakhand: "UK",
  "West Bengal": "WB",
};
