#!/bin/sh

echo "🔍 Validating commit message..."

COMMIT_MSG_REGEX="^(feat|fix|docs|style|refactor|test|chore|revert|ci|perf)(\(.+\))?: .{1,50}$"

COMMIT_MSG_FILE=$1
COMMIT_MSG=$(cat $COMMIT_MSG_FILE)

if ! echo "$COMMIT_MSG" | grep -Eq "$COMMIT_MSG_REGEX"; then
  echo "❌ Invalid commit message format."
  echo "⚠️  Commit message must follow the Conventional Commit format:"
  echo "   <type>(<scope>): <short description>"
  echo ""
  echo "   Example: feat(navbar): add navigation bar"
  echo ""
  exit 1
fi

echo "✅ Commit message format is valid."
