#!/bin/sh
. "$(dirname "$0")/_/h"

# Regex to validate commit message
commit_regex="^(feat|fix|docs|style|refactor|perf|test|chore|ci|build|revert)(\(.+\))?: .{1,72}$"

commit_message=$(cat "$1")

if ! echo "$commit_message" | grep -Eq "$commit_regex"; then
  echo "❌ Invalid commit message format!"
  echo ""
  echo "✅ Valid format: <type>(<scope>): <message>"
  echo "   where <type> is one of: feat, fix, docs, style, refactor, perf, test, chore, ci, build, revert"
  echo "   <scope> is optional and can be omitted."
  echo ""
  exit 1
fi
