#!/usr/bin/env sh
. "$(dirname "$0")/_/husky.sh"

echo "🔍 Running biome check..."
yarn biome check --write
RESULT=$?
if [ $RESULT -ne 0 ]; then
  echo "❌ Biome check failed. Commit aborted."
  exit 1
fi
echo "✅ Biome check passed. Proceeding with commit."
